# Generated by Django 4.0.2 on 2022-02-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0023_teamscore_result_alter_hostmatch_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buisness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buisness_name', models.CharField(blank=True, max_length=200, null=True)),
                ('buisness_image', models.ImageField(blank=True, null=True, upload_to='buisness_image')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('buisness_hours', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buisness.service')),
            ],
        ),
    ]
