# Generated by Django 4.0.2 on 2022-02-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0002_short_images_buisness_short_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='buisness',
            name='tennis_court',
            field=models.IntegerField(default=0),
        ),
    ]
