# Generated by Django 4.0.2 on 2022-02-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0003_buisness_tennis_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='tennis_court',
            field=models.IntegerField(blank=True),
        ),
    ]
