# Generated by Django 4.0.2 on 2022-02-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0005_alter_buisness_tennis_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='buisness',
            name='buisness_days',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
