# Generated by Django 4.0.2 on 2022-02-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0006_buisness_buisness_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buisness',
            old_name='buisness_days',
            new_name='non_working_days',
        ),
        migrations.RenameField(
            model_name='buisness',
            old_name='buisness_hours',
            new_name='non_working_hours',
        ),
        migrations.AddField(
            model_name='buisness',
            name='working_days',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buisness',
            name='working_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
