# Generated by Django 4.0.2 on 2022-02-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0007_rename_buisness_days_buisness_non_working_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buisness',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buisness',
            name='long',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buisness',
            name='pin_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
