# Generated by Django 4.0.2 on 2022-03-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0009_remove_buisness_profile_buisness_buisness_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='short_images',
            field=models.ManyToManyField(blank=True, null=True, to='buisness.Short_Images'),
        ),
    ]
