# Generated by Django 4.0.2 on 2022-03-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0012_remove_buisness_service_buisness_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buisness',
            name='short_images',
        ),
        migrations.DeleteModel(
            name='Short_Images',
        ),
    ]
