# Generated by Django 4.0.2 on 2022-03-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0013_remove_buisness_short_images_delete_short_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='buisness',
            name='short_images',
            field=models.ImageField(blank=True, null=True, upload_to='short_buisness_images'),
        ),
    ]
