# Generated by Django 4.0.2 on 2022-03-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_rename_user_id_hostmatch_profile_id'),
        ('buisness', '0015_remove_buisness_short_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='buisness_owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buisness_owner', to='user.profile'),
        ),
    ]
