# Generated by Django 4.0.2 on 2022-03-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0020_alter_buisnessimages_buisness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buisness',
            name='buisness_image',
        ),
    ]
