# Generated by Django 4.0.2 on 2022-03-10 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buisness', '0022_alter_buisness_buisness_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='buisness_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buisness_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buisness',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
