# Generated by Django 4.0.2 on 2022-03-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0025_alter_buisnessimages_buisness_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisnessimages',
            name='buisness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buisness_images', to='buisness.buisness'),
        ),
    ]
