# Generated by Django 4.0.2 on 2022-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0026_alter_buisnessimages_buisness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisnessimages',
            name='buisness_images',
            field=models.ImageField(default=None, upload_to='buisnessimages'),
        ),
    ]
