# Generated by Django 4.0.2 on 2022-03-15 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0030_alter_buisnessimages_buisness'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuisnessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.CharField(blank=True, max_length=100, null=True)),
                ('close_time', models.CharField(blank=True, max_length=100, null=True)),
                ('buisness_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buisness.buisness')),
            ],
        ),
    ]
