# Generated by Django 4.0.2 on 2022-03-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0031_buisnesshours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buisness',
            name='non_working_days',
        ),
        migrations.RemoveField(
            model_name='buisness',
            name='non_working_hours',
        ),
        migrations.RemoveField(
            model_name='buisness',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='buisness',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='buisness',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='buisness',
            name='cpf_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='buisness',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buisnesshours',
            name='day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200, null=True),
        ),
    ]
