# Generated by Django 4.0.2 on 2022-03-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0032_remove_buisness_non_working_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buisness',
            old_name='buisness_owner',
            new_name='user_id',
        ),
    ]
