# Generated by Django 4.0.2 on 2022-03-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0033_rename_buisness_owner_buisness_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buisness',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
