# Generated by Django 4.0.2 on 2022-04-01 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0035_remove_buisness_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('buisness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buisness.buisness')),
            ],
        ),
    ]
