# Generated by Django 4.0.2 on 2022-02-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_suspend_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suspend_User',
        ),
    ]
