# Generated by Django 4.0.2 on 2022-02-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_delete_suspend_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buisness',
        ),
    ]
