# Generated by Django 4.0.2 on 2022-02-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
