# Generated by Django 4.0.2 on 2022-02-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_hostmatch_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostmatch',
            name='host_match',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
