# Generated by Django 4.0.2 on 2022-02-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_hostmatch_host_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamscore',
            name='user_invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.hostinvitation'),
        ),
        migrations.RemoveField(
            model_name='hostinvitation',
            name='user_invited',
        ),
        migrations.AddField(
            model_name='hostinvitation',
            name='user_invited',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile', to='user.Profile'),
        ),
    ]
