# Generated by Django 4.0.2 on 2022-02-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_teamscore_user_invited_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamscore',
            old_name='user_invited',
            new_name='host_invited',
        ),
        migrations.RemoveField(
            model_name='hostinvitation',
            name='user_invited',
        ),
        migrations.AddField(
            model_name='hostinvitation',
            name='user_invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='user.profile'),
        ),
    ]
