# Generated by Django 4.0.2 on 2022-02-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_rename_user_invited_teamscore_host_invited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='matchhost',
        ),
    ]
