# Generated by Django 4.0.2 on 2022-02-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_profile_matchhost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostmatch',
            name='host_match',
        ),
    ]
