# Generated by Django 4.0.2 on 2022-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_hostmatch_host_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hostmatch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
