# Generated by Django 4.0.2 on 2022-02-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_remove_notification_dateadded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='Status',
        ),
    ]
