# Generated by Django 4.0.2 on 2022-02-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_remove_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
