# Generated by Django 4.0.2 on 2022-02-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_notification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamscore',
            name='host_invited',
        ),
        migrations.AddField(
            model_name='hostmatch',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostmatch',
            name='long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostmatch',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
