# Generated by Django 4.0.2 on 2022-02-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_remove_teamscore_host_invited_hostmatch_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='country',
        ),
    ]
