# Generated by Django 4.0.2 on 2022-02-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_rename_city_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('buisness', 'buisness')], max_length=100, null=True),
        ),
    ]
