# Generated by Django 4.0.2 on 2022-02-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_usertype_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
