# Generated by Django 4.0.2 on 2022-02-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_remove_user_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
