# Generated by Django 4.0.2 on 2022-02-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
