# Generated by Django 4.0.2 on 2022-02-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_alter_usertype_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
