# Generated by Django 4.0.2 on 2022-02-28 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, null=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to='user.usertype'),
            preserve_default=-1,
        ),
    ]
