# Generated by Django 4.0.2 on 2022-02-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
