# Generated by Django 4.0.2 on 2022-02-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buisness', '0009_remove_buisness_profile_buisness_buisness_owner'),
        ('user', '0054_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_buisness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buisness.buisness'),
        ),
    ]
