# Generated by Django 4.0.2 on 2022-02-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_user_user_buisness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_buisness',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
