# Generated by Django 4.0.2 on 2022-03-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_profile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostmatch',
            old_name='user_id',
            new_name='profile_id',
        ),
    ]
