# Generated by Django 4.0.2 on 2022-03-11 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_alter_aboutus_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='termscondition',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
