# Generated by Django 4.0.2 on 2022-03-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_termscondition_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='long',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
