# Generated by Django 4.0.2 on 2022-03-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0063_profile_avg_rating_alter_profile_hostmatch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
