# Generated by Django 4.0.2 on 2022-03-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0064_delete_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avg_rating',
            new_name='rating',
        ),
    ]
