# Generated by Django 4.0.2 on 2022-03-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_remove_profile_rating_alter_playersrating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersrating',
            name='host_match',
        ),
    ]
