# Generated by Django 4.0.2 on 2022-03-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_remove_playersrating_host_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmatch',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostmatch',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
