# Generated by Django 4.0.2 on 2022-03-24 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='to_user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='from_user',
            new_name='sender',
        ),
    ]
