# Generated by Django 4.0.2 on 2022-03-25 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_alter_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersrating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
