# Generated by Django 4.0.2 on 2022-03-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0076_alter_playersrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
