# Generated by Django 4.0.2 on 2022-03-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_profile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinvitation',
            name='user_invited',
        ),
        migrations.AddField(
            model_name='hostinvitation',
            name='user_invited',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_invited_profile', to='user.Profile'),
        ),
    ]
