# Generated by Django 4.0.2 on 2022-03-25 12:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_remove_hostinvitation_user_invited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinvitation',
            name='user_invited',
            field=models.ManyToManyField(related_name='user_invited_profile', to='user.Profile'),
        ),
        # migrations.AlterField(
        #     model_name='hostmatch',
        #     name='location',
        #     field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        # ),
    ]
