# Generated by Django 4.0.2 on 2022-03-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0080_remove_hostmatch_location'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='hostmatch',
    #         name='location',
    #         field=models.CharField(blank=True, max_length=200, null=True),
    #     ),
    # ]
