# Generated by Django 4.0.2 on 2022-03-25 12:48

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0083_alter_hostmatch_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmatch',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
