# Generated by Django 4.0.2 on 2022-03-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0085_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
