# Generated by Django 4.0.2 on 2022-03-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0087_alter_hostmatch_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostmatch',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='hostmatch',
            name='long',
        ),
    ]
