# Generated by Django 4.0.2 on 2022-03-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0089_remove_hostmatch_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinvitation',
            name='user_invited',
            field=models.ManyToManyField(related_name='user_invited_profile', to='user.FriendRequest'),
        ),
    ]
