# Generated by Django 4.0.2 on 2022-03-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0091_alter_hostinvitation_user_invited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinvitation',
            name='user_invited',
        ),
    ]
