# Generated by Django 4.0.2 on 2022-04-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0094_alter_hostinvitation_user_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostmatch',
            name='player_counts',
            field=models.IntegerField(default=0),
        ),
    ]
